version: '3.8'

services:
  protobuf-builder:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "protoc --proto_path=proto --go_out=gen/go --go-grpc_out=gen/go proto/**/*.proto"