# See: https://taskfile.dev/api/

version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate code from proto files"
    cmds:
      - protoc --proto_path=proto --go_out=gen/go --go-grpc_out=gen/go proto/**/*.proto
  generate-docker:
    aliases:
      - gen-d
    desc: "Generate code from proto files with docker"
    cmds:
      - docker run --rm -v ${PWD}:/app -w /app protoc-gen ./protoc-gen.sh
  build-docker:
    aliases:
      - build-d
    desc: "build docker container"
    cmds:
      - docker build -t protoc-gen .
